service: ListAllNFTs

provider:
  name: aws
  stage: nfts
  runtime: nodejs12.x
  profile: default
  timeout: 30

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:*"
      Resource: "*"


functions:
  listAllNFTs:
    handler: handler.listAllNFTs
    name: ListAllNFTs
    memorySize: 512
    events:
      - http:
            path: /list
            method: get
